# Generated by Django 2.1.5 on 2020-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proggrammer',
            name='language',
            field=models.ManyToManyField(to='relations.Languages'),
        ),
        migrations.RemoveField(
            model_name='proggrammer',
            name='name',
        ),
        migrations.AddField(
            model_name='proggrammer',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
