# Generated by Django 2.1.5 on 2020-10-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20)),
                ('post_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField(default=0)),
                ('dislikes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='rates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onetoone.PostRates'),
        ),
    ]
