# Generated by Django 2.1.5 on 2020-10-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('car_warranty', models.PositiveIntegerField(default=1)),
                ('finance_plan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('production_yr', models.IntegerField()),
                ('car_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytoone.Carplan')),
            ],
        ),
    ]
