# Generated by Django 2.1.5 on 2020-10-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('yr_warranty', models.PositiveIntegerField(default=1)),
                ('finance_yr', models.CharField(default='Unavalable', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarSpacs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=25)),
                ('car_model', models.CharField(max_length=25)),
                ('product_yr', models.CharField(max_length=25)),
                ('car_body', models.CharField(max_length=25)),
                ('engine_type', models.CharField(max_length=25)),
                ('car_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manyone1.CarPlan')),
            ],
        ),
    ]
